### ISSUE TITLE
Uncaught DOMException: Failed to execute 'postMessage' on 'Window'

### ISSUE THREAD

**Issue by silviubogan** [zendive/jsdiff#6]
Hello!

I would love to be able to use this extension but I get this error:

![image](https://user-images.githubusercontent.com/198924/93352142-30983480-f843-11ea-8a3b-c2acf6c7b92e.png)

Thank you!

**Comment by zendive** [comment]
@silviubogan Thanks!

The exceptions shows the unavailability to post message from yours site window context to the extension window context, as some object values can't be messaged to the extension, such as functions.
The v1.1 extension assumed to work only on plain objects, thus implying more accurate manual selections of objects and type of their properties for comparison.

Probably there is a better way to handle message passing. So in v2.0 you should be able to compare objects having functions and objects containing reoccurring references. Please try a new version when it comes out (already submitted for chrome web-store review) or try to load it unpacked from [v2.0](https://github.com/zendive/jsdiff/tree/v2.0) branch before that.
